# Generated by Django 6.1 on 2026-09-04 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('usual_cycle_length', models.PositiveIntegerField(default=28)),
                ('usual_period_duration', models.PositiveIntegerField(default=5)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('irregular', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('predicted_cycle_length', models.PositiveIntegerField(blank=True, null=True)),
                ('predicted_next_period', models.DateField(blank=True, null=True)),
                ('predicted_next_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_reminder', models.BooleanField(default=True)),
                ('reminder_days_before', models.PositiveIntegerField(default=3)),
                ('symptom_reminder', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cramps', models.PositiveIntegerField(default=0)),
                ('headache', models.BooleanField(default=False)),
                ('flow', models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], max_length=20)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('normal', 'Normal'), ('sad', 'Sad'), ('irritable', 'Irritable'), ('anxious', 'Anxious')], max_length=20)),
                ('stress_level', models.PositiveIntegerField(default=1)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
